import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const PLAN_LIMITS = [
  {
    plan: "FREE" as const,
    maxActiveSessions: 2,
    maxPlayersPerSession: 5,
    allowPublicSessions: false,
    allowAsyncSessions: false,
    maxMapUploadMb: 5,
    maxAiMapsPerMonth: 0,
    allowFogOfWar: false,
    maxMapLayers: 0,
    allowDynamicLighting: false,
    allowLineOfSight: false,
    allowInpainting: false,
    maxCharactersPerPlayer: 3,
    allowContextualRolls: false,
    allowPdfExport: false,
    availableSheetTemplates: JSON.stringify(["generic"]),
    allowWhisper: false,
    allowSecretNotes: false,
    maxFileUploadMb: 2,
    allowPlayerFileSharing: false,
    allowProgressiveReveal: false,
    maxStorageMb: 50,
    allowSoundtrack: false,
    soundtrackTier: "none",
    allowCustomAudioUpload: false,
    allowNpcAssistant: false,
    allowAiTimeline: false,
    maxFriends: 50,
    allowInitiativeTracker: false,
    maxPersonalStorageMb: 0,
    allowPersonalVault: false,
    allowProfileBadge: false,
    badgeName: null,
  },
  {
    plan: "ADVENTURER" as const,
    maxActiveSessions: 8,
    maxPlayersPerSession: 10,
    allowPublicSessions: true,
    allowAsyncSessions: true,
    maxMapUploadMb: 20,
    maxAiMapsPerMonth: 20,
    allowFogOfWar: true,
    maxMapLayers: 3,
    allowDynamicLighting: false,
    allowLineOfSight: false,
    allowInpainting: false,
    maxCharactersPerPlayer: 10,
    allowContextualRolls: true,
    allowPdfExport: true,
    availableSheetTemplates: JSON.stringify(["generic", "dnd5e", "tormenta20"]),
    allowWhisper: true,
    allowSecretNotes: true,
    maxFileUploadMb: 5,
    allowPlayerFileSharing: true,
    allowProgressiveReveal: true,
    maxStorageMb: 3072,
    allowSoundtrack: true,
    soundtrackTier: "builtin",
    allowCustomAudioUpload: false,
    allowNpcAssistant: false,
    allowAiTimeline: false,
    maxFriends: 200,
    allowInitiativeTracker: true,
    maxPersonalStorageMb: 0,
    allowPersonalVault: false,
    allowProfileBadge: false,
    badgeName: null,
  },
  {
    plan: "LEGENDARY" as const,
    maxActiveSessions: 9999,
    maxPlayersPerSession: 20,
    allowPublicSessions: true,
    allowAsyncSessions: true,
    maxMapUploadMb: 50,
    maxAiMapsPerMonth: 9999,
    allowFogOfWar: true,
    maxMapLayers: 9999,
    allowDynamicLighting: true,
    allowLineOfSight: true,
    allowInpainting: true,
    maxCharactersPerPlayer: 9999,
    allowContextualRolls: true,
    allowPdfExport: true,
    availableSheetTemplates: JSON.stringify(["all"]),
    allowWhisper: true,
    allowSecretNotes: true,
    maxFileUploadMb: 50,
    allowPlayerFileSharing: true,
    allowProgressiveReveal: true,
    maxStorageMb: 30720,
    allowSoundtrack: true,
    soundtrackTier: "full",
    allowCustomAudioUpload: true,
    allowNpcAssistant: true,
    allowAiTimeline: true,
    maxFriends: 9999,
    allowInitiativeTracker: true,
    maxPersonalStorageMb: 0,
    allowPersonalVault: false,
    allowProfileBadge: true,
    badgeName: "Mestre Lendário",
  },
  {
    plan: "PLAYER_PLUS" as const,
    maxActiveSessions: 0,
    maxPlayersPerSession: 0,
    allowPublicSessions: false,
    allowAsyncSessions: false,
    maxMapUploadMb: 0,
    maxAiMapsPerMonth: 0,
    allowFogOfWar: false,
    maxMapLayers: 0,
    allowDynamicLighting: false,
    allowLineOfSight: false,
    allowInpainting: false,
    maxCharactersPerPlayer: 9999,
    allowContextualRolls: false,
    allowPdfExport: true,
    availableSheetTemplates: JSON.stringify(["all"]),
    allowWhisper: false,
    allowSecretNotes: false,
    maxFileUploadMb: 0,
    allowPlayerFileSharing: false,
    allowProgressiveReveal: false,
    maxStorageMb: 0,
    allowSoundtrack: false,
    soundtrackTier: "none",
    allowCustomAudioUpload: false,
    allowNpcAssistant: false,
    allowAiTimeline: false,
    maxFriends: 9999,
    allowInitiativeTracker: false,
    maxPersonalStorageMb: 5120,
    allowPersonalVault: true,
    allowProfileBadge: true,
    badgeName: "Jogador Dedicado",
  },
];

const ACHIEVEMENTS = [
  // ── Sessions ──
  {
    key: "first_session",
    name: "Primeira Aventura",
    description: "Participe da sua primeira sessão",
    category: "SESSIONS" as const,
    rarity: "COMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalSessions", threshold: 1 },
    reward: { badge: "first_adventure", xp: 100 },
    sortOrder: 1,
  },
  {
    key: "sessions_10",
    name: "Aventureiro Dedicado",
    description: "Participe de 10 sessões",
    category: "SESSIONS" as const,
    rarity: "UNCOMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalSessions", threshold: 10 },
    reward: { badge: "dedicated_adventurer", xp: 500 },
    sortOrder: 2,
  },
  {
    key: "sessions_50",
    name: "Veterano",
    description: "Participe de 50 sessões",
    category: "SESSIONS" as const,
    rarity: "RARE" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalSessions", threshold: 50 },
    reward: { badge: "veteran", xp: 2000 },
    sortOrder: 3,
  },
  {
    key: "sessions_100",
    name: "Lenda Viva",
    description: "Participe de 100 sessões",
    category: "SESSIONS" as const,
    rarity: "EPIC" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalSessions", threshold: 100 },
    reward: { badge: "living_legend", xp: 5000 },
    sortOrder: 4,
  },
  {
    key: "first_gm",
    name: "Primeiro Mestre",
    description: "Mestre sua primeira sessão",
    category: "SESSIONS" as const,
    rarity: "COMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalSessionsAsGm", threshold: 1 },
    reward: { badge: "first_gm", xp: 200 },
    sortOrder: 5,
  },
  {
    key: "gm_50",
    name: "Mestre Experiente",
    description: "Mestre 50 sessões",
    category: "SESSIONS" as const,
    rarity: "EPIC" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalSessionsAsGm", threshold: 50 },
    reward: { badge: "experienced_gm", xp: 5000, title: "Mestre Experiente" },
    sortOrder: 6,
  },
  // ── Combat / Dice ──
  {
    key: "dice_100",
    name: "Rolador Iniciante",
    description: "Role 100 dados",
    category: "COMBAT" as const,
    rarity: "COMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalDiceRolled", threshold: 100 },
    reward: { xp: 100 },
    sortOrder: 10,
  },
  {
    key: "dice_1000",
    name: "Mestre dos Dados",
    description: "Role 1.000 dados",
    category: "COMBAT" as const,
    rarity: "RARE" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalDiceRolled", threshold: 1000 },
    reward: { badge: "dice_master", xp: 2000 },
    sortOrder: 11,
  },
  {
    key: "natural_20",
    name: "Golpe de Sorte",
    description: "Tire um natural 20",
    category: "COMBAT" as const,
    rarity: "COMMON" as const,
    triggerType: "event",
    triggerConfig: { type: "event", event: "natural_20" },
    reward: { xp: 50 },
    sortOrder: 12,
  },
  {
    key: "nat20_50",
    name: "Abençoado pelos Dados",
    description: "Tire 50 naturais 20",
    category: "COMBAT" as const,
    rarity: "RARE" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalNat20s", threshold: 50 },
    reward: { badge: "blessed_by_dice", xp: 2000 },
    sortOrder: 13,
  },
  {
    key: "natural_1",
    name: "Falha Crítica",
    description: "Tire um natural 1",
    category: "COMBAT" as const,
    rarity: "COMMON" as const,
    triggerType: "event",
    triggerConfig: { type: "event", event: "natural_1" },
    reward: { xp: 25 },
    sortOrder: 14,
  },
  // ── Social ──
  {
    key: "first_friend",
    name: "Companheiro de Aventura",
    description: "Adicione seu primeiro amigo",
    category: "SOCIAL" as const,
    rarity: "COMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalFriendsAdded", threshold: 1 },
    reward: { xp: 50 },
    sortOrder: 20,
  },
  {
    key: "friends_10",
    name: "Guilda de Amigos",
    description: "Tenha 10 amigos",
    category: "SOCIAL" as const,
    rarity: "UNCOMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalFriendsAdded", threshold: 10 },
    reward: { badge: "friend_guild", xp: 300 },
    sortOrder: 21,
  },
  {
    key: "chat_100",
    name: "Tagarela",
    description: "Envie 100 mensagens no chat",
    category: "SOCIAL" as const,
    rarity: "COMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalMessagesInChat", threshold: 100 },
    reward: { xp: 100 },
    sortOrder: 22,
  },
  {
    key: "chat_1000",
    name: "Bardo",
    description: "Envie 1.000 mensagens no chat",
    category: "SOCIAL" as const,
    rarity: "RARE" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalMessagesInChat", threshold: 1000 },
    reward: { badge: "bard", xp: 1000, title: "Bardo" },
    sortOrder: 23,
  },
  // ── Creation ──
  {
    key: "first_character",
    name: "Nascimento de um Herói",
    description: "Crie seu primeiro personagem",
    category: "CREATION" as const,
    rarity: "COMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalCharactersCreated", threshold: 1 },
    reward: { xp: 100 },
    sortOrder: 30,
  },
  {
    key: "characters_10",
    name: "Criador de Heróis",
    description: "Crie 10 personagens",
    category: "CREATION" as const,
    rarity: "UNCOMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalCharactersCreated", threshold: 10 },
    reward: { badge: "hero_creator", xp: 500 },
    sortOrder: 31,
  },
  // ── Dedication ──
  {
    key: "streak_4",
    name: "Maratonista",
    description: "Jogue por 4 semanas consecutivas",
    category: "DEDICATION" as const,
    rarity: "UNCOMMON" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "currentWeeklyStreak", threshold: 4 },
    reward: { badge: "marathoner", xp: 500 },
    sortOrder: 40,
  },
  {
    key: "streak_12",
    name: "Inabalável",
    description: "Jogue por 12 semanas consecutivas",
    category: "DEDICATION" as const,
    rarity: "RARE" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "currentWeeklyStreak", threshold: 12 },
    reward: { badge: "unshakeable", xp: 2000, title: "Inabalável" },
    sortOrder: 41,
  },
  {
    key: "hours_100",
    name: "Centenário",
    description: "Acumule 100 horas em sessões",
    category: "DEDICATION" as const,
    rarity: "EPIC" as const,
    triggerType: "counter",
    triggerConfig: { type: "counter", stat: "totalSessionMinutes", threshold: 6000 },
    reward: { badge: "centenarian", xp: 5000 },
    sortOrder: 42,
  },
];

async function main() {
  console.log("Seeding database...");

  // ── Plan Limits ──
  for (const limit of PLAN_LIMITS) {
    await prisma.planLimit.upsert({
      where: { plan: limit.plan },
      update: limit,
      create: limit,
    });
  }
  console.log(`  - Plan limits: ${PLAN_LIMITS.length} plans seeded`);

  // ── Achievements ──
  for (const achievement of ACHIEVEMENTS) {
    await prisma.achievement.upsert({
      where: { key: achievement.key },
      update: {
        name: achievement.name,
        description: achievement.description,
        category: achievement.category,
        rarity: achievement.rarity,
        triggerType: achievement.triggerType,
        triggerConfig: achievement.triggerConfig,
        reward: achievement.reward,
        sortOrder: achievement.sortOrder,
      },
      create: achievement,
    });
  }
  console.log(`  - Achievements: ${ACHIEVEMENTS.length} achievements seeded`);

  // ── Character Templates ──
  const dnd5eTemplate = await prisma.characterTemplate.upsert({
    where: { system_name: { system: "dnd5e", name: "Standard" } },
    update: {},
    create: {
      system: "dnd5e",
      name: "Standard",
      schema: {
        fields: [
          { key: "class", label: "Classe", type: "text" },
          { key: "race", label: "Raça", type: "text" },
          { key: "level", label: "Nível", type: "number", min: 1, max: 20 },
          { key: "hp", label: "Pontos de Vida", type: "number" },
          { key: "ac", label: "Classe de Armadura", type: "number" },
          { key: "str", label: "Força", type: "number", min: 1, max: 30 },
          { key: "dex", label: "Destreza", type: "number", min: 1, max: 30 },
          { key: "con", label: "Constituição", type: "number", min: 1, max: 30 },
          { key: "int", label: "Inteligência", type: "number", min: 1, max: 30 },
          { key: "wis", label: "Sabedoria", type: "number", min: 1, max: 30 },
          { key: "cha", label: "Carisma", type: "number", min: 1, max: 30 },
        ],
      },
      version: 1,
    },
  });

  const genericTemplate = await prisma.characterTemplate.upsert({
    where: { system_name: { system: "generic", name: "Simple" } },
    update: {},
    create: {
      system: "generic",
      name: "Simple",
      schema: {
        fields: [
          { key: "description", label: "Descrição", type: "textarea" },
          { key: "notes", label: "Notas", type: "textarea" },
        ],
      },
      version: 1,
    },
  });

  // ── Audio Tracks ──
  await prisma.audioTrack.createMany({
    skipDuplicates: true,
    data: [
      { category: "tavern", name: "Taverna Animada", url: "/audio/tavern-lively.mp3", duration: 180, isBuiltin: true },
      { category: "forest", name: "Floresta Calma", url: "/audio/forest-calm.mp3", duration: 240, isBuiltin: true },
      { category: "combat", name: "Batalha Épica", url: "/audio/combat-epic.mp3", duration: 200, isBuiltin: true },
      { category: "dungeon", name: "Masmorra Sombria", url: "/audio/dungeon-dark.mp3", duration: 300, isBuiltin: true },
      { category: "ambient", name: "Chuva", url: "/audio/rain-ambient.mp3", duration: 600, isBuiltin: true },
    ],
  });

  console.log("Seed completed.");
  console.log(`  - D&D 5e template: ${dnd5eTemplate.id}`);
  console.log(`  - Generic template: ${genericTemplate.id}`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
