// ── SFX Definitions ──
// Each definition maps a game event to an optimized Freesound query.
// The engine searches, downloads the best-rated preview, and caches in IndexedDB.

export interface SFXDefinition {
  id: string;
  name: string;
  category: string;
  query: string;
  fallbackQueries: string[];
  filter: string;
  maxDuration: number;
  minDuration: number;
  minRating: number;
  volume: number;
}

export const SFX_DEFINITIONS: SFXDefinition[] = [
  // ── Dice ──
  {
    id: "dice-roll",
    name: "Rolar Dados",
    category: "dice",
    query: "dice roll table",
    fallbackQueries: ["rolling dice", "dice throw", "tabletop dice"],
    filter: "duration:[0.5 TO 3]",
    maxDuration: 3,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "dice-result",
    name: "Resultado do Dado",
    category: "dice",
    query: "ui confirm positive chime",
    fallbackQueries: ["notification chime", "positive ding", "success sound short"],
    filter: "duration:[0.1 TO 1]",
    maxDuration: 1,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.4,
  },
  {
    id: "nat20",
    name: "Nat 20 (Crítico!)",
    category: "dice",
    query: "fanfare victory short",
    fallbackQueries: ["triumph short", "epic success fanfare", "achievement unlocked sound"],
    filter: "duration:[0.5 TO 3]",
    maxDuration: 3,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "nat1",
    name: "Nat 1 (Falha Crítica)",
    category: "dice",
    query: "fail trombone sad",
    fallbackQueries: ["failure horn", "sad trombone", "game over fail short"],
    filter: "duration:[0.5 TO 3]",
    maxDuration: 3,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.6,
  },

  // ── Combat — Melee ──
  {
    id: "sword-hit",
    name: "Espada Acertou",
    category: "combat",
    query: "sword hit metal clash",
    fallbackQueries: ["sword impact", "metal weapon hit", "blade strike"],
    filter: "duration:[0.1 TO 2]",
    maxDuration: 2,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "sword-miss",
    name: "Espada Errou (Swoosh)",
    category: "combat",
    query: "sword swing swoosh",
    fallbackQueries: ["weapon swoosh", "blade swing air", "whoosh sword"],
    filter: "duration:[0.1 TO 1.5]",
    maxDuration: 1.5,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "blunt-hit",
    name: "Arma Contundente",
    category: "combat",
    query: "blunt hit impact body",
    fallbackQueries: ["mace impact", "hammer hit", "punch impact heavy"],
    filter: "duration:[0.1 TO 1.5]",
    maxDuration: 1.5,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.7,
  },

  // ── Combat — Ranged ──
  {
    id: "arrow-shot",
    name: "Flecha Disparada",
    category: "combat",
    query: "bow arrow release",
    fallbackQueries: ["arrow shot bow", "bowstring release", "arrow fly"],
    filter: "duration:[0.1 TO 2]",
    maxDuration: 2,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "arrow-hit",
    name: "Flecha Acertou",
    category: "combat",
    query: "arrow impact thud",
    fallbackQueries: ["arrow hit target", "arrow thunk wood", "projectile impact"],
    filter: "duration:[0.1 TO 1.5]",
    maxDuration: 1.5,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.6,
  },

  // ── Combat — Magic ──
  {
    id: "magic-cast",
    name: "Conjurar Magia",
    category: "magic",
    query: "magic spell cast fantasy",
    fallbackQueries: ["spell casting", "magical power up", "arcane energy"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "magic-hit",
    name: "Magia Acertou",
    category: "magic",
    query: "magic impact hit energy",
    fallbackQueries: ["spell impact", "magical explosion hit", "energy burst"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "fire-spell",
    name: "Magia de Fogo",
    category: "magic",
    query: "fireball explosion magic fire",
    fallbackQueries: ["fire burst", "flame explosion", "fire magic whoosh"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "ice-spell",
    name: "Magia de Gelo",
    category: "magic",
    query: "ice freeze magic crystal",
    fallbackQueries: ["frozen ice crack", "ice spell fantasy", "frost magic"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "lightning-spell",
    name: "Magia de Raio",
    category: "magic",
    query: "lightning bolt electricity zap",
    fallbackQueries: ["electric shock", "thunder bolt", "lightning strike short"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "heal-spell",
    name: "Cura / Buff",
    category: "magic",
    query: "healing magic sparkle positive",
    fallbackQueries: ["heal spell", "positive magic chime", "buff power up fantasy"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "dark-spell",
    name: "Magia Sombria",
    category: "magic",
    query: "dark magic evil spell",
    fallbackQueries: ["necrotic spell", "shadow magic", "dark energy"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "shield-spell",
    name: "Escudo Mágico",
    category: "magic",
    query: "magic shield block force field",
    fallbackQueries: ["energy shield activate", "barrier magic", "protection spell"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.5,
  },

  // ── Combat — Damage & Death ──
  {
    id: "take-damage",
    name: "Tomar Dano",
    category: "combat",
    query: "body hit punch impact",
    fallbackQueries: ["flesh impact", "getting hit", "body punch thud"],
    filter: "duration:[0.1 TO 1.5]",
    maxDuration: 1.5,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "creature-death",
    name: "Criatura Morreu",
    category: "combat",
    query: "death groan creature monster",
    fallbackQueries: ["creature dying", "monster death", "enemy defeated"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "shield-block",
    name: "Escudo Bloqueou",
    category: "combat",
    query: "shield block metal clang",
    fallbackQueries: ["shield impact", "metal shield hit", "block sword shield"],
    filter: "duration:[0.1 TO 2]",
    maxDuration: 2,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "explosion",
    name: "Explosão",
    category: "combat",
    query: "explosion boom short",
    fallbackQueries: ["big explosion", "bomb explosion short", "blast short"],
    filter: "duration:[0.3 TO 4]",
    maxDuration: 4,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.8,
  },
  {
    id: "critical-hit",
    name: "Golpe Crítico",
    category: "combat",
    query: "critical hit powerful slash",
    fallbackQueries: ["heavy weapon impact", "powerful strike", "devastating blow"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.8,
  },

  // ── UI & Turn ──
  {
    id: "turn-change",
    name: "Mudança de Turno",
    category: "ui",
    query: "bell chime notification gentle",
    fallbackQueries: ["turn signal ding", "soft bell ring", "notification bell"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.4,
  },
  {
    id: "my-turn",
    name: "Seu Turno!",
    category: "ui",
    query: "attention alert horn epic short",
    fallbackQueries: ["war horn short", "call to action", "battle alert signal"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "chat-message",
    name: "Mensagem no Chat",
    category: "ui",
    query: "pop bubble notification soft",
    fallbackQueries: ["message pop", "notification pop short", "soft blip"],
    filter: "duration:[0.05 TO 0.5]",
    maxDuration: 0.5,
    minDuration: 0.05,
    minRating: 2,
    volume: 0.3,
  },
  {
    id: "notification",
    name: "Notificação",
    category: "ui",
    query: "notification ding subtle",
    fallbackQueries: ["alert ding", "subtle notification bell"],
    filter: "duration:[0.1 TO 1]",
    maxDuration: 1,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.4,
  },
  {
    id: "success",
    name: "Confirmação",
    category: "ui",
    query: "success confirm positive",
    fallbackQueries: ["positive confirmation ding", "task complete chime"],
    filter: "duration:[0.1 TO 1]",
    maxDuration: 1,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.4,
  },
  {
    id: "error",
    name: "Erro",
    category: "ui",
    query: "error buzz negative wrong",
    fallbackQueries: ["error sound", "wrong buzzer", "negative alert"],
    filter: "duration:[0.1 TO 1]",
    maxDuration: 1,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.4,
  },
  {
    id: "opportunity-attack",
    name: "Ataque de Oportunidade",
    category: "ui",
    query: "sword unsheathe alert metal",
    fallbackQueries: ["blade draw alert", "sword draw quick", "weapon ready alert"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.7,
  },

  // ── Session ──
  {
    id: "player-join",
    name: "Jogador Conectou",
    category: "session",
    query: "join chime ascending positive",
    fallbackQueries: ["connect chime", "welcome ding ascending"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.4,
  },
  {
    id: "player-leave",
    name: "Jogador Desconectou",
    category: "session",
    query: "disconnect chime descending",
    fallbackQueries: ["leave chime", "farewell ding descending", "logout sound"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.4,
  },
  {
    id: "combat-start",
    name: "Combate Iniciou",
    category: "session",
    query: "battle start drum war",
    fallbackQueries: ["combat begin drums", "fight start", "war drum roll short"],
    filter: "duration:[0.5 TO 4]",
    maxDuration: 4,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "combat-end",
    name: "Combate Encerrou",
    category: "session",
    query: "victory fanfare rpg short",
    fallbackQueries: ["battle won", "victory jingle", "quest complete fanfare"],
    filter: "duration:[1 TO 5]",
    maxDuration: 5,
    minDuration: 1,
    minRating: 3,
    volume: 0.6,
  },

  // ── World / Map ──
  {
    id: "door-open",
    name: "Porta Abrindo",
    category: "world",
    query: "wooden door open creak",
    fallbackQueries: ["door opening creak", "old door open", "dungeon door"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "door-close",
    name: "Porta Fechando",
    category: "world",
    query: "door close shut wooden",
    fallbackQueries: ["door slam", "door close heavy", "wooden door shut"],
    filter: "duration:[0.2 TO 2]",
    maxDuration: 2,
    minDuration: 0.2,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "door-locked",
    name: "Porta Trancada",
    category: "world",
    query: "door locked rattle handle",
    fallbackQueries: ["locked door attempt", "door handle rattle locked"],
    filter: "duration:[0.3 TO 2]",
    maxDuration: 2,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "chest-open",
    name: "Baú Abrindo",
    category: "world",
    query: "treasure chest open wooden",
    fallbackQueries: ["chest opening creak", "wooden box lid open", "loot box open"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "coin-drop",
    name: "Moedas (Loot)",
    category: "world",
    query: "coins drop gold jingling",
    fallbackQueries: ["gold coins falling", "coin pile drop", "money coins clink"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "potion-drink",
    name: "Beber Poção",
    category: "world",
    query: "potion drink gulp magic",
    fallbackQueries: ["drinking potion", "gulp liquid", "swallow drink bottle"],
    filter: "duration:[0.3 TO 2]",
    maxDuration: 2,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "level-up",
    name: "Level Up",
    category: "world",
    query: "level up rpg game",
    fallbackQueries: ["power up game", "level up jingle", "experience gain sound"],
    filter: "duration:[0.5 TO 4]",
    maxDuration: 4,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "trap-trigger",
    name: "Armadilha Ativou",
    category: "world",
    query: "trap trigger click mechanism",
    fallbackQueries: ["trap activated", "mechanism trigger click", "spring trap snap"],
    filter: "duration:[0.1 TO 2]",
    maxDuration: 2,
    minDuration: 0.1,
    minRating: 3,
    volume: 0.6,
  },
  {
    id: "footsteps-stone",
    name: "Passos em Pedra",
    category: "world",
    query: "footsteps stone dungeon echo",
    fallbackQueries: ["walking stone floor", "footsteps cave", "steps dungeon"],
    filter: "duration:[0.5 TO 3]",
    maxDuration: 3,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.3,
  },

  // ── Soundboard (ambient one-shots) ──
  {
    id: "ambient-thunder",
    name: "Trovão",
    category: "soundboard",
    query: "thunder rumble short",
    fallbackQueries: ["thunderclap", "thunder crack short", "storm thunder close"],
    filter: "duration:[0.5 TO 5]",
    maxDuration: 5,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.7,
  },
  {
    id: "ambient-wolf-howl",
    name: "Uivo de Lobo",
    category: "soundboard",
    query: "wolf howl night",
    fallbackQueries: ["wolf howling", "lone wolf howl", "wolves howl"],
    filter: "duration:[1 TO 6]",
    maxDuration: 6,
    minDuration: 1,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "ambient-evil-laugh",
    name: "Risada Maligna",
    category: "soundboard",
    query: "evil laugh villain",
    fallbackQueries: ["sinister laugh", "wicked laugh", "maniacal laugh short"],
    filter: "duration:[0.5 TO 4]",
    maxDuration: 4,
    minDuration: 0.5,
    minRating: 3,
    volume: 0.5,
  },
  {
    id: "ambient-scream",
    name: "Grito de Horror",
    category: "soundboard",
    query: "scream horror scary",
    fallbackQueries: ["terrified scream", "horror scream short", "frightened yell"],
    filter: "duration:[0.3 TO 3]",
    maxDuration: 3,
    minDuration: 0.3,
    minRating: 3,
    volume: 0.5,
  },
];
