export enum Plan {
  FREE = "FREE",
  ADVENTURER = "ADVENTURER",
  LEGENDARY = "LEGENDARY",
  PLAYER_PLUS = "PLAYER_PLUS",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  TRIALING = "TRIALING",
  PAST_DUE = "PAST_DUE",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  PAUSED = "PAUSED",
}

export enum BillingCycle {
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  REFUNDED = "REFUNDED",
  CHARGED_BACK = "CHARGED_BACK",
}

export enum FriendshipStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
}

export enum AchievementCategory {
  SESSIONS = "SESSIONS",
  COMBAT = "COMBAT",
  SOCIAL = "SOCIAL",
  CREATION = "CREATION",
  EXPLORATION = "EXPLORATION",
  DEDICATION = "DEDICATION",
  SPECIAL = "SPECIAL",
}

export enum AchievementRarity {
  COMMON = "COMMON",
  UNCOMMON = "UNCOMMON",
  RARE = "RARE",
  EPIC = "EPIC",
  LEGENDARY = "LEGENDARY",
}

export enum NotificationType {
  SESSION_INVITE = "SESSION_INVITE",
  SESSION_STARTING = "SESSION_STARTING",
  SESSION_LIVE = "SESSION_LIVE",
  SESSION_ENDED = "SESSION_ENDED",
  SESSION_KICK = "SESSION_KICK",
  FRIEND_REQUEST = "FRIEND_REQUEST",
  FRIEND_ACCEPTED = "FRIEND_ACCEPTED",
  FRIEND_ONLINE = "FRIEND_ONLINE",
  ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  TRIAL_ENDING = "TRIAL_ENDING",
  PLAN_CHANGED = "PLAN_CHANGED",
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
  SYSTEM_UPDATE = "SYSTEM_UPDATE",
}

export enum SessionType {
  PRIVATE = "PRIVATE",
  PUBLIC = "PUBLIC",
  ASYNC = "ASYNC",
}

export enum SessionStatus {
  IDLE = "IDLE",
  LIVE = "LIVE",
  PAUSED = "PAUSED",
  ENDED = "ENDED",
  ARCHIVED = "ARCHIVED",
}

export enum SessionVisibility {
  UNLISTED = "UNLISTED",
  LISTED = "LISTED",
  FRIENDS_ONLY = "FRIENDS_ONLY",
}

export enum PlayerRole {
  GM = "GM",
  CO_GM = "CO_GM",
  PLAYER = "PLAYER",
  SPECTATOR = "SPECTATOR",
}

export enum RsvpStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  DECLINED = "DECLINED",
  TENTATIVE = "TENTATIVE",
}

export enum InviteStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  EXPIRED = "EXPIRED",
  REVOKED = "REVOKED",
}

export enum ScheduleStatus {
  SCHEDULED = "SCHEDULED",
  STARTED = "STARTED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  SKIPPED = "SKIPPED",
}

export enum ReportReason {
  HARASSMENT = "HARASSMENT",
  HATE_SPEECH = "HATE_SPEECH",
  INAPPROPRIATE = "INAPPROPRIATE",
  SPAM = "SPAM",
  CHEATING = "CHEATING",
  IMPERSONATION = "IMPERSONATION",
  OTHER = "OTHER",
}

export enum ReportStatus {
  OPEN = "OPEN",
  UNDER_REVIEW = "UNDER_REVIEW",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
}

export enum GridType {
  SQUARE = "SQUARE",
  HEX_FLAT = "HEX_FLAT",
  HEX_POINTY = "HEX_POINTY",
  NONE = "NONE",
}

export enum MapGenerationStatus {
  QUEUED = "QUEUED",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  FAILED = "FAILED",
}

export enum TokenType {
  PC = "PC",
  NPC = "NPC",
  ENEMY = "ENEMY",
  ALLY = "ALLY",
  OBJECT = "OBJECT",
  VEHICLE = "VEHICLE",
  EFFECT = "EFFECT",
}

export enum FogShapeType {
  RECTANGLE = "RECTANGLE",
  CIRCLE = "CIRCLE",
  POLYGON = "POLYGON",
  FREEHAND = "FREEHAND",
  CELL = "CELL",
}

export enum WallType {
  NORMAL = "NORMAL",
  WINDOW = "WINDOW",
  ETHEREAL = "ETHEREAL",
  INVISIBLE = "INVISIBLE",
  TERRAIN = "TERRAIN",
}

export enum DoorState {
  CLOSED = "CLOSED",
  OPEN = "OPEN",
  LOCKED = "LOCKED",
  SECRET = "SECRET",
}

export enum LightType {
  POINT = "POINT",
  CONE = "CONE",
  AMBIENT = "AMBIENT",
}

export enum LayerContentType {
  IMAGE = "IMAGE",
  DRAWING = "DRAWING",
}

export enum AnnotationType {
  FREEHAND = "FREEHAND",
  ARROW = "ARROW",
  CIRCLE = "CIRCLE",
  RECTANGLE = "RECTANGLE",
  TEXT = "TEXT",
  RULER = "RULER",
  CONE = "CONE",
  SPHERE = "SPHERE",
  LINE = "LINE",
  CUBE = "CUBE",
}

export enum AnnotationVisibility {
  ALL = "ALL",
  GM_ONLY = "GM_ONLY",
  SPECIFIC = "SPECIFIC",
}

export enum InteractionType {
  DOOR = "DOOR",
  CHEST = "CHEST",
  LEVER = "LEVER",
  NPC_TALK = "NPC_TALK",
  EXAMINE = "EXAMINE",
  TELEPORT = "TELEPORT",
  TRAP = "TRAP",
  PICKUP = "PICKUP",
  CUSTOM = "CUSTOM",
}

export enum ZoneType {
  DIFFICULT_TERRAIN = "DIFFICULT_TERRAIN",
  HAZARD = "HAZARD",
  DARKNESS = "DARKNESS",
  AMBIENT_SOUND = "AMBIENT_SOUND",
  NARRATIVE = "NARRATIVE",
  ANTI_MAGIC = "ANTI_MAGIC",
  CONCEALMENT = "CONCEALMENT",
  TRIGGER = "TRIGGER",
  SAFE_ZONE = "SAFE_ZONE",
  CUSTOM = "CUSTOM",
}

export enum ExplorationEvent {
  DOOR_OPENED = "DOOR_OPENED",
  DOOR_CLOSED = "DOOR_CLOSED",
  DOOR_LOCKED = "DOOR_LOCKED",
  DOOR_UNLOCKED = "DOOR_UNLOCKED",
  OBJECT_USED = "OBJECT_USED",
  ZONE_ENTERED = "ZONE_ENTERED",
  ZONE_EXITED = "ZONE_EXITED",
  TRAP_TRIGGERED = "TRAP_TRIGGERED",
  TRAP_DISARMED = "TRAP_DISARMED",
  NPC_TALKED = "NPC_TALKED",
  AREA_DISCOVERED = "AREA_DISCOVERED",
  ITEM_PICKED_UP = "ITEM_PICKED_UP",
  TELEPORTED = "TELEPORTED",
  MAP_CHANGED = "MAP_CHANGED",
  NARRATIVE_SHOWN = "NARRATIVE_SHOWN",
  SECRET_FOUND = "SECRET_FOUND",
  SKILL_CHECK_MADE = "SKILL_CHECK_MADE",
  TOKEN_MOVED = "TOKEN_MOVED",
}

export enum MapGenMode {
  TEXT_TO_MAP = "TEXT_TO_MAP",
  VARIATION = "VARIATION",
  INPAINT = "INPAINT",
  ENHANCE = "ENHANCE",
  WALLS_DETECT = "WALLS_DETECT",
}

export enum ChatChannel {
  GENERAL = "GENERAL",
  IN_CHARACTER = "IN_CHARACTER",
  WHISPER = "WHISPER",
  GM_ONLY = "GM_ONLY",
  GROUP = "GROUP",
}

export enum MessageType {
  TEXT = "TEXT",
  DICE_ROLL = "DICE_ROLL",
  SYSTEM = "SYSTEM",
  MEDIA = "MEDIA",
  NARRATIVE = "NARRATIVE",
}

export enum DiceRollMode {
  PUBLIC = "PUBLIC",
  GM_ONLY = "GM_ONLY",
  SELF = "SELF",
}

// ── Character & Template Enums ──

export enum TemplateTier {
  FREE = "FREE",
  ADVENTURER = "ADVENTURER",
  LEGENDARY = "LEGENDARY",
}

export enum CharacterStatus {
  ACTIVE = "ACTIVE",
  RETIRED = "RETIRED",
  DEAD = "DEAD",
  ARCHIVED = "ARCHIVED",
}

export enum VaultFileType {
  IMAGE = "IMAGE",
  DOCUMENT = "DOCUMENT",
  AUDIO = "AUDIO",
  SHEET_EXPORT = "SHEET_EXPORT",
  OTHER = "OTHER",
}

export enum DiceRollType {
  MANUAL = "MANUAL",
  ABILITY_CHECK = "ABILITY_CHECK",
  SAVING_THROW = "SAVING_THROW",
  ATTACK = "ATTACK",
  DAMAGE = "DAMAGE",
  SPELL_ATTACK = "SPELL_ATTACK",
  SPELL_DAMAGE = "SPELL_DAMAGE",
  INITIATIVE = "INITIATIVE",
  HIT_DICE = "HIT_DICE",
  DEATH_SAVE = "DEATH_SAVE",
  CUSTOM = "CUSTOM",
}

export enum DiceVisibility {
  PUBLIC = "PUBLIC",
  GM_ONLY = "GM_ONLY",
  WHISPER = "WHISPER",
  SELF = "SELF",
}

export enum ShareTargetType {
  GM = "GM",
  CO_GM = "CO_GM",
  ALL_PLAYERS = "ALL_PLAYERS",
  SPECIFIC_USER = "SPECIFIC_USER",
}
