export enum Plan {
  FREE = "FREE",
  ADVENTURER = "ADVENTURER",
  LEGENDARY = "LEGENDARY",
  PLAYER_PLUS = "PLAYER_PLUS",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  TRIALING = "TRIALING",
  PAST_DUE = "PAST_DUE",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  PAUSED = "PAUSED",
}

export enum BillingCycle {
  MONTHLY = "MONTHLY",
  YEARLY = "YEARLY",
}

export enum PaymentStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  REFUNDED = "REFUNDED",
  CHARGED_BACK = "CHARGED_BACK",
}

export enum FriendshipStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
}

export enum AchievementCategory {
  SESSIONS = "SESSIONS",
  COMBAT = "COMBAT",
  SOCIAL = "SOCIAL",
  CREATION = "CREATION",
  EXPLORATION = "EXPLORATION",
  DEDICATION = "DEDICATION",
  SPECIAL = "SPECIAL",
}

export enum AchievementRarity {
  COMMON = "COMMON",
  UNCOMMON = "UNCOMMON",
  RARE = "RARE",
  EPIC = "EPIC",
  LEGENDARY = "LEGENDARY",
}

export enum NotificationType {
  SESSION_INVITE = "SESSION_INVITE",
  SESSION_STARTING = "SESSION_STARTING",
  SESSION_LIVE = "SESSION_LIVE",
  SESSION_ENDED = "SESSION_ENDED",
  SESSION_KICK = "SESSION_KICK",
  FRIEND_REQUEST = "FRIEND_REQUEST",
  FRIEND_ACCEPTED = "FRIEND_ACCEPTED",
  FRIEND_ONLINE = "FRIEND_ONLINE",
  ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  TRIAL_ENDING = "TRIAL_ENDING",
  PLAN_CHANGED = "PLAN_CHANGED",
  SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT",
  SYSTEM_UPDATE = "SYSTEM_UPDATE",
}

export enum SessionType {
  PRIVATE = "PRIVATE",
  PUBLIC = "PUBLIC",
  ASYNC = "ASYNC",
}

export enum SessionStatus {
  IDLE = "IDLE",
  LIVE = "LIVE",
  PAUSED = "PAUSED",
  ENDED = "ENDED",
}

export enum PlayerRole {
  GM = "GM",
  CO_GM = "CO_GM",
  PLAYER = "PLAYER",
  SPECTATOR = "SPECTATOR",
}

export enum GridType {
  SQUARE = "SQUARE",
  HEX = "HEX",
}

export enum MapGenerationStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
}

export enum ChatChannel {
  GENERAL = "GENERAL",
  IN_CHARACTER = "IN_CHARACTER",
  WHISPER = "WHISPER",
  GM_ONLY = "GM_ONLY",
  GROUP = "GROUP",
}

export enum MessageType {
  TEXT = "TEXT",
  DICE_ROLL = "DICE_ROLL",
  SYSTEM = "SYSTEM",
  MEDIA = "MEDIA",
  NARRATIVE = "NARRATIVE",
}

export enum DiceRollMode {
  PUBLIC = "PUBLIC",
  GM_ONLY = "GM_ONLY",
  SELF = "SELF",
}
