import type { CampaignCharacter } from "@/types/character";

export const MOCK_CHARACTERS: CampaignCharacter[] = [
  {
    id: "char_tavern_01",
    name: "Bardo, o Taverneiro",
    title: "Dono da Taverna do Grifo",
    description:
      "Homem robusto de barba grisalha. Conhece todos os rumores da regiao e serve a melhor cerveja da cidade.",
    category: "npc",
    role: "merchant",
    disposition: "friendly",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#FDCB6E",
    stats: {
      hp: 14,
      maxHp: 14,
      ac: 10,
      speed: 30,
      str: 12,
      dex: 10,
      con: 12,
      int: 11,
      wis: 14,
      cha: 15,
      languages: ["Comum"],
    },
    actions: [
      {
        id: "act_tavern_01",
        name: "Porrete",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 3,
        damage: "1d4+1",
        damageType: "contundente",
        reach: 5,
      },
    ],
    traits: "Sempre limpa canecas enquanto conversa.",
    dialogueEnabled: true,
    dialogueGreeting: "Bem-vindos ao Grifo! O que vao querer hoje?",
    dialogueNotes:
      "Sabe sobre a masmorra ao norte. Revela informacoes se os jogadores pagarem uma rodada.",
    createdByUserId: "user-1",
    isPublic: false,
    favorite: true,
    createdAt: "2025-01-10T10:00:00Z",
    updatedAt: "2025-01-10T10:00:00Z",
  },
  {
    id: "char_guard_02",
    name: "Capitao Aldric",
    title: "Capitao da Guarda Real",
    description:
      "Veterano de guerra com uma cicatriz no rosto. Leal ao rei, desconfia de aventureiros.",
    category: "npc",
    role: "ally",
    disposition: "neutral",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#74B9FF",
    stats: {
      hp: 52,
      maxHp: 52,
      ac: 18,
      speed: 30,
      cr: "3",
      str: 16,
      dex: 12,
      con: 14,
      int: 11,
      wis: 13,
      cha: 14,
      savingThrows: ["STR", "CON"],
      skills: ["Athletics", "Perception"],
      languages: ["Comum", "Elfico"],
    },
    actions: [
      {
        id: "act_guard_01",
        name: "Espada Longa",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 5,
        damage: "1d8+3",
        damageType: "cortante",
        reach: 5,
      },
      {
        id: "act_guard_02",
        name: "Comando de Lideranca",
        description:
          "Aliados num raio de 30ft ganham +1d4 na proxima jogada de ataque.",
        isReaction: true,
      },
    ],
    dialogueEnabled: true,
    dialogueGreeting: "Identifiquem-se. O que querem na cidade?",
    createdByUserId: "user-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-11T10:00:00Z",
    updatedAt: "2025-01-11T10:00:00Z",
  },
  {
    id: "char_witch_03",
    name: "Morgana, a Bruxa",
    title: "Senhora da Floresta Negra",
    description:
      "Velha encorvada com olhos brilhantes. Oferece pactos perigosos e pocoes duvidosas.",
    category: "npc",
    role: "villain",
    disposition: "hostile",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#8B5CF6",
    stats: {
      hp: 40,
      maxHp: 40,
      ac: 12,
      speed: 30,
      cr: "5",
      str: 8,
      dex: 14,
      con: 12,
      int: 18,
      wis: 16,
      cha: 14,
      savingThrows: ["INT", "WIS"],
      skills: ["Arcana", "Deception", "Nature"],
      senses: "Darkvision 60ft",
      languages: ["Comum", "Silvano", "Infernal"],
    },
    actions: [
      {
        id: "act_witch_01",
        name: "Raio de Gelo",
        description: "Ataque a distancia com magia.",
        attackBonus: 7,
        damage: "3d8",
        damageType: "gelo",
      },
      {
        id: "act_witch_02",
        name: "Maldição",
        description:
          "O alvo deve fazer um teste de resistencia de Sabedoria (CD 15) ou ficar amaldicoado por 1 hora.",
      },
    ],
    traits: "Resistencia a magia. Pode conjurar Disfarce a vontade.",
    dialogueEnabled: true,
    dialogueGreeting: "Que coragem... ou tolice. O que buscam em meu dominio?",
    dialogueNotes: "Falar com voz rascante. Oferece informacoes por um preco.",
    createdByUserId: "user-1",
    isPublic: false,
    favorite: true,
    createdAt: "2025-01-12T10:00:00Z",
    updatedAt: "2025-01-12T10:00:00Z",
  },
  {
    id: "char_goblin_04",
    name: "Goblin Explorador",
    description: "Goblin agil e furtivo. Sempre acompanhado de outros.",
    category: "creature",
    creatureType: "humanoide",
    disposition: "hostile",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#00B894",
    stats: {
      hp: 7,
      maxHp: 7,
      ac: 15,
      speed: 30,
      cr: "1/4",
      str: 8,
      dex: 14,
      con: 10,
      int: 10,
      wis: 8,
      cha: 8,
      skills: ["Stealth"],
      senses: "Darkvision 60ft",
      languages: ["Comum", "Goblin"],
    },
    actions: [
      {
        id: "act_goblin_01",
        name: "Cimitarra",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 4,
        damage: "1d6+2",
        damageType: "cortante",
        reach: 5,
      },
      {
        id: "act_goblin_02",
        name: "Arco Curto",
        description: "Ataque a distancia com arma.",
        attackBonus: 4,
        damage: "1d6+2",
        damageType: "perfurante",
      },
    ],
    traits: "Fuga Agil: pode usar acao bonus para Desengajar ou Esconder.",
    dialogueEnabled: false,
    createdByUserId: "user-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-13T10:00:00Z",
    updatedAt: "2025-01-13T10:00:00Z",
  },
  {
    id: "char_skeleton_05",
    name: "Esqueleto Guerreiro",
    description:
      "Ossos animados por magia negra. Obedece cegamente seu mestre necromante.",
    category: "creature",
    creatureType: "morto-vivo",
    disposition: "undead",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#6B7280",
    stats: {
      hp: 13,
      maxHp: 13,
      ac: 13,
      speed: 30,
      cr: "1/4",
      str: 10,
      dex: 14,
      con: 15,
      int: 6,
      wis: 8,
      cha: 5,
      damageImmunities: ["veneno"],
      conditionImmunities: ["envenenado", "exausto"],
      senses: "Darkvision 60ft",
      languages: ["Entende Comum mas nao fala"],
    },
    actions: [
      {
        id: "act_skel_01",
        name: "Espada Curta",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 4,
        damage: "1d6+2",
        damageType: "perfurante",
        reach: 5,
      },
    ],
    dialogueEnabled: false,
    createdByUserId: "user-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-14T10:00:00Z",
    updatedAt: "2025-01-14T10:00:00Z",
  },
  {
    id: "char_dragon_06",
    name: "Fafnir, o Vermelho",
    title: "Dragao Anciao Vermelho",
    description:
      "Dragao milenar que habita o vulcao ao leste. Coleciona riquezas e adora enigmas.",
    category: "creature",
    role: "boss",
    creatureType: "dragao",
    disposition: "hostile",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#FF4444",
    stats: {
      hp: 256,
      maxHp: 256,
      ac: 22,
      speed: 40,
      cr: "17",
      str: 27,
      dex: 10,
      con: 25,
      int: 16,
      wis: 13,
      cha: 21,
      savingThrows: ["DEX", "CON", "WIS", "CHA"],
      skills: ["Perception", "Stealth"],
      damageImmunities: ["fogo"],
      senses: "Blindsight 60ft, Darkvision 120ft",
      languages: ["Comum", "Draconico"],
    },
    actions: [
      {
        id: "act_dragon_01",
        name: "Mordida",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 14,
        damage: "2d10+8",
        damageType: "perfurante",
        reach: 10,
      },
      {
        id: "act_dragon_02",
        name: "Garras",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 14,
        damage: "2d6+8",
        damageType: "cortante",
        reach: 5,
      },
      {
        id: "act_dragon_03",
        name: "Sopro de Fogo",
        description:
          "Cone de 60ft. Cada criatura deve fazer teste de DEX (CD 21) ou sofrer 18d6 de dano de fogo.",
      },
      {
        id: "act_dragon_04",
        name: "Acao Lendaria: Ataque de Cauda",
        description: "O dragao faz um ataque de cauda.",
        attackBonus: 14,
        damage: "2d8+8",
        damageType: "contundente",
        reach: 15,
        isLegendary: true,
      },
    ],
    traits:
      "Resistencia Lendaria (3/dia). Presenca Aterrorizante: criaturas num raio de 120ft devem fazer teste de SAB (CD 19) ou ficar amedrontadas.",
    dialogueEnabled: true,
    dialogueGreeting:
      "Mortais ousados... divirtam-me com um enigma ou sirvam de refeicao.",
    dialogueNotes: "Voz grave e ressonante. Gosta de brincar com a comida.",
    createdByUserId: "user-1",
    isPublic: false,
    favorite: true,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "char_dwarf_07",
    name: "Durgan Forjafogo",
    title: "Mestre Ferreiro",
    description:
      "Anao de barba ruiva trancada. Forja as melhores armas da regiao, mas exige materiais raros.",
    category: "npc",
    role: "merchant",
    disposition: "friendly",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#E17055",
    stats: {
      hp: 30,
      maxHp: 30,
      ac: 14,
      speed: 25,
      str: 16,
      dex: 10,
      con: 16,
      int: 13,
      wis: 12,
      cha: 10,
      damageImmunities: ["fogo"],
      languages: ["Comum", "Anao"],
    },
    actions: [
      {
        id: "act_dwarf_01",
        name: "Martelo de Guerra",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 5,
        damage: "1d8+3",
        damageType: "contundente",
        reach: 5,
      },
    ],
    dialogueEnabled: true,
    dialogueGreeting:
      "Ha! Clientes! Venham ver minhas ultimas criacoes. Nao encontram melhor em lugar nenhum!",
    createdByUserId: "user-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-16T10:00:00Z",
    updatedAt: "2025-01-16T10:00:00Z",
  },
  {
    id: "char_priestess_08",
    name: "Selene Lunaris",
    title: "Sacerdotisa do Templo da Lua",
    description:
      "Elfa de cabelos prateados. Guarda segredos antigos e pode curar ferimentos graves.",
    category: "npc",
    role: "quest",
    disposition: "friendly",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#A29BFE",
    stats: {
      hp: 27,
      maxHp: 27,
      ac: 13,
      speed: 30,
      cr: "2",
      str: 10,
      dex: 12,
      con: 12,
      int: 14,
      wis: 18,
      cha: 16,
      savingThrows: ["WIS", "CHA"],
      skills: ["Medicine", "Religion", "Insight"],
      senses: "Darkvision 60ft",
      languages: ["Comum", "Elfico", "Celestial"],
    },
    actions: [
      {
        id: "act_priest_01",
        name: "Fogo Sagrado",
        description:
          "O alvo deve fazer teste de DEX (CD 14) ou sofrer 2d8 de dano radiante.",
      },
      {
        id: "act_priest_02",
        name: "Curar Ferimentos",
        description: "Toque restaura 2d8+4 pontos de vida.",
      },
    ],
    traits: "Pode conjurar Zona da Verdade uma vez por dia.",
    dialogueEnabled: true,
    dialogueGreeting:
      "Que a luz da Lua os guie. Como posso ajuda-los, viajantes?",
    dialogueNotes:
      "Falar com serenidade. Sabe sobre a profecia mas so revela apos provar confianca.",
    createdByUserId: "user-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-17T10:00:00Z",
    updatedAt: "2025-01-17T10:00:00Z",
  },
  {
    id: "char_ogre_09",
    name: "Ogro das Cavernas",
    description:
      "Criatura enorme e estupida. Devora tudo que encontra em seu caminho.",
    category: "creature",
    creatureType: "gigante",
    disposition: "hostile",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#A0522D",
    stats: {
      hp: 59,
      maxHp: 59,
      ac: 11,
      speed: 40,
      cr: "2",
      str: 19,
      dex: 8,
      con: 16,
      int: 5,
      wis: 7,
      cha: 7,
      senses: "Darkvision 60ft",
      languages: ["Comum", "Gigante"],
    },
    actions: [
      {
        id: "act_ogre_01",
        name: "Clava Grande",
        description: "Ataque corpo a corpo com arma.",
        attackBonus: 6,
        damage: "2d8+4",
        damageType: "contundente",
        reach: 5,
      },
      {
        id: "act_ogre_02",
        name: "Arremessar Pedra",
        description: "Ataque a distancia com arma improvised.",
        attackBonus: 6,
        damage: "2d6+4",
        damageType: "contundente",
      },
    ],
    dialogueEnabled: false,
    createdByUserId: "user-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-18T10:00:00Z",
    updatedAt: "2025-01-18T10:00:00Z",
  },
  {
    id: "char_wolf_10",
    name: "Lobo Sombrio",
    description:
      "Lobo negro de olhos vermelhos. Mais inteligente que um lobo comum — guiado por magia sombria.",
    category: "creature",
    creatureType: "monstruosidade",
    disposition: "hostile",
    spriteUrl: null,
    spriteGeneratedByAI: false,
    portraitUrl: undefined,
    portraitColor: "#6B7280",
    stats: {
      hp: 22,
      maxHp: 22,
      ac: 13,
      speed: 50,
      cr: "1",
      str: 15,
      dex: 13,
      con: 13,
      int: 7,
      wis: 12,
      cha: 6,
      skills: ["Perception", "Stealth"],
      senses: "Darkvision 120ft",
      languages: ["Entende Comum e Goblin"],
    },
    actions: [
      {
        id: "act_wolf_01",
        name: "Mordida",
        description:
          "Ataque corpo a corpo. O alvo deve fazer teste de FOR (CD 13) ou cair.",
        attackBonus: 4,
        damage: "2d6+2",
        damageType: "perfurante",
        reach: 5,
      },
    ],
    traits:
      "Faro Aguçado: vantagem em testes de Percepcao (olfato). Tatica de Matilha: vantagem no ataque se aliado adjacente.",
    dialogueEnabled: false,
    createdByUserId: "user-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-19T10:00:00Z",
    updatedAt: "2025-01-19T10:00:00Z",
  },
];
