import type { CampaignObject, MapObjectInstance } from "@/types/object";

export const MOCK_OBJECTS: CampaignObject[] = [
  // ── Cenário ──
  {
    id: "obj_mesa_taverna",
    name: "Mesa de Taverna",
    description: "Uma mesa de madeira rústica com marcas de canecas e facas.",
    category: "scenery",
    rarity: "comum",
    tags: ["mobília", "taverna"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "🪵",
    spriteColor: "#A0522D",
    blocking: true,
    isConsumable: false,
    interactionEnabled: false,
    interactionEffects: [],
    widthCells: 2,
    heightCells: 1,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-15T10:00:00Z",
    updatedAt: "2025-01-15T10:00:00Z",
  },
  {
    id: "obj_altar_antigo",
    name: "Altar Antigo",
    description: "Um altar de pedra negra coberto com runas brilhantes. Emana uma energia sinistra.",
    category: "scenery",
    rarity: "raro",
    tags: ["pedra", "mágico", "templo"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "⛩️",
    spriteColor: "#6C5CE7",
    blocking: true,
    lightRadius: 2,
    lightColor: "#8B5CF6",
    isConsumable: false,
    interactionEnabled: true,
    interactionLabel: "Examinar",
    interactionEffects: [
      { id: "eff_1", type: "trigger_event", label: "Ativar ritual", data: {} },
    ],
    widthCells: 2,
    heightCells: 2,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: true,
    createdAt: "2025-01-10T08:00:00Z",
    updatedAt: "2025-02-01T14:00:00Z",
  },
  {
    id: "obj_tocha_parede",
    name: "Tocha de Parede",
    description: "Uma tocha cravada na parede que ilumina os corredores da masmorra.",
    category: "scenery",
    rarity: "comum",
    tags: ["luz", "masmorra"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "🔥",
    spriteColor: "#F59E0B",
    blocking: false,
    lightRadius: 4,
    lightColor: "#FFF4C2",
    isConsumable: false,
    interactionEnabled: false,
    interactionEffects: [],
    widthCells: 1,
    heightCells: 1,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-12T09:00:00Z",
    updatedAt: "2025-01-12T09:00:00Z",
  },
  {
    id: "obj_fonte_magica",
    name: "Fonte Mágica",
    description: "Uma fonte de mármore branco com água que brilha em azul. Quem beber recupera 1d6 HP.",
    category: "scenery",
    rarity: "muito_raro",
    tags: ["mágico", "cura", "água"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "⛲",
    spriteColor: "#74B9FF",
    blocking: true,
    lightRadius: 3,
    lightColor: "#74B9FF",
    isConsumable: false,
    interactionEnabled: true,
    interactionLabel: "Beber",
    interactionEffects: [
      { id: "eff_2", type: "custom_note", label: "Beber da fonte", data: { text: "Voce bebe a agua brilhante e recupera 1d6 pontos de vida." } },
    ],
    widthCells: 2,
    heightCells: 2,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: true,
    createdAt: "2025-01-08T12:00:00Z",
    updatedAt: "2025-01-20T16:00:00Z",
  },
  {
    id: "obj_estatua_dragao",
    name: "Estátua de Dragão",
    description: "Uma imponente estátua de pedra representando um dragão antigo com asas abertas.",
    category: "scenery",
    rarity: "incomum",
    tags: ["pedra", "decoração", "dragão"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "🐉",
    spriteColor: "#6B7280",
    blocking: true,
    isConsumable: false,
    interactionEnabled: false,
    interactionEffects: [],
    widthCells: 2,
    heightCells: 2,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-14T11:00:00Z",
    updatedAt: "2025-01-14T11:00:00Z",
  },

  // ── Itens ──
  {
    id: "obj_espada_solar",
    name: "Espada Solar",
    description: "Uma lâmina forjada com metal celestial que emite luz dourada. +2 para atacar mortos-vivos.",
    category: "item",
    rarity: "lendario",
    tags: ["arma", "espada", "sagrado"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "⚔️",
    spriteColor: "#FFD700",
    blocking: false,
    weight: 3,
    value: 12000,
    isConsumable: false,
    interactionEnabled: true,
    interactionLabel: "Pegar",
    interactionEffects: [
      { id: "eff_3", type: "give_item", label: "Pegar espada", data: {} },
      { id: "eff_4", type: "reveal_fog", label: "Revelar area", data: { radius: 5 } },
    ],
    linkedNarrativeNodeId: "node-1",
    widthCells: 1,
    heightCells: 1,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: true,
    createdAt: "2025-01-05T14:00:00Z",
    updatedAt: "2025-02-10T09:00:00Z",
  },
  {
    id: "obj_amuleto_strahd",
    name: "Amuleto de Strahd",
    description: "Um medalhão escuro com uma gema vermelha que pulsa como um coração.",
    category: "item",
    rarity: "lendario",
    tags: ["acessório", "amaldiçoado", "vampiro"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "💎",
    spriteColor: "#FF4757",
    blocking: false,
    weight: 0.5,
    value: 25000,
    isConsumable: false,
    interactionEnabled: true,
    interactionLabel: "Examinar",
    interactionEffects: [
      { id: "eff_5", type: "trigger_event", label: "Ativar visao", data: {} },
    ],
    linkedNarrativeNodeId: "node-2",
    widthCells: 1,
    heightCells: 1,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: true,
    createdAt: "2025-01-03T10:00:00Z",
    updatedAt: "2025-01-28T18:00:00Z",
  },
  {
    id: "obj_pocao_cura",
    name: "Poção de Cura",
    description: "Um frasco com líquido vermelho brilhante. Recupera 2d4+2 pontos de vida.",
    category: "item",
    rarity: "comum",
    tags: ["poção", "cura", "consumível"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "🧪",
    spriteColor: "#FF6B6B",
    blocking: false,
    weight: 0.5,
    value: 50,
    isConsumable: true,
    charges: 1,
    interactionEnabled: true,
    interactionLabel: "Usar",
    interactionEffects: [
      { id: "eff_6", type: "custom_note", label: "Beber poção", data: { text: "Voce bebe a poção e recupera 2d4+2 HP." } },
    ],
    widthCells: 1,
    heightCells: 1,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-20T15:00:00Z",
    updatedAt: "2025-01-20T15:00:00Z",
  },
  {
    id: "obj_pergaminho_antigo",
    name: "Pergaminho Antigo",
    description: "Um pergaminho envelhecido com escritas em Infernal. Contém pistas sobre a maldição.",
    category: "item",
    rarity: "raro",
    tags: ["documento", "mágico", "pista"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "📜",
    spriteColor: "#C9A84C",
    blocking: false,
    weight: 0.1,
    value: 200,
    isConsumable: false,
    interactionEnabled: true,
    interactionLabel: "Ler",
    interactionEffects: [
      { id: "eff_7", type: "show_handout", label: "Mostrar texto", data: {} },
    ],
    widthCells: 1,
    heightCells: 1,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-18T13:00:00Z",
    updatedAt: "2025-01-18T13:00:00Z",
  },
  {
    id: "obj_bau_tesouro",
    name: "Baú do Tesouro",
    description: "Um baú de madeira reforçada com detalhes dourados. Parece estar trancado.",
    category: "item",
    rarity: "incomum",
    tags: ["container", "tesouro", "trancado"],
    spriteUrl: null,
    spriteGeneratedByAI: false,
    spriteEmoji: "📦",
    spriteColor: "#E17055",
    blocking: true,
    isConsumable: false,
    interactionEnabled: true,
    interactionLabel: "Abrir",
    interactionEffects: [
      { id: "eff_8", type: "open_door", label: "Destrancar", data: {} },
      { id: "eff_9", type: "play_sound", label: "Som de abertura", data: { soundKey: "chest_open" } },
    ],
    widthCells: 1,
    heightCells: 1,
    campaignId: "campaign-1",
    isPublic: false,
    favorite: false,
    createdAt: "2025-01-22T16:00:00Z",
    updatedAt: "2025-01-22T16:00:00Z",
  },
];

export const MOCK_MAP_OBJECT_INSTANCES: MapObjectInstance[] = [
  { id: "inst_1", objectId: "obj_tocha_parede", mapId: "map-1", col: 3, row: 2, rotation: 0, scale: 1, visible: true },
  { id: "inst_2", objectId: "obj_mesa_taverna", mapId: "map-1", col: 8, row: 5, rotation: 0, scale: 1, visible: true },
  { id: "inst_3", objectId: "obj_bau_tesouro", mapId: "map-1", col: 15, row: 10, rotation: 0, scale: 1, visible: true },
];
