// ── Seed mock de magias do SRD 5.1 ──
//
// 15 magias canônicas escolhidas pra cobrir variedade (truques,
// buffs, dano, controle, cura, utility) e testar filtros. Quando o
// importer existir, esse arquivo some em favor da DB. Por ora serve
// pra UI do compêndio funcionar.
//
// Conteúdo: SRD 5.1 (CC-BY 4.0). Tradução pt-BR baseada em termos
// consagrados; revisão humana fica pra fatia futura.

import type { SrdSpell } from "@/types/srd";
import { makeOfficialSrdAttribution } from "./attribution";

const ATTR = makeOfficialSrdAttribution("SRD 5.1 §5");

export const SEED_SPELLS: SrdSpell[] = [
  {
    slug: "fire-bolt",
    name: "Raio de Fogo",
    nameEn: "Fire Bolt",
    level: 0,
    school: "evocation",
    castingTime: "1 ação",
    range: "36 metros",
    components: ["V", "S"],
    duration: "Instantâneo",
    description:
      "Você arremessa um dardo de chamas em uma criatura ou objeto à distância. Faça uma jogada de ataque mágico à distância contra o alvo. Em um acerto, o alvo sofre 1d10 de dano de fogo. Um objeto inflamável atingido por essa magia se incendeia se não estiver sendo carregado ou vestido.",
    higherLevels:
      "O dano da magia aumenta em 1d10 ao alcançar o 5º nível (2d10), 11º (3d10) e 17º (4d10) níveis.",
    ritual: false,
    concentration: false,
    damageDice: "1d10",
    damageType: "fire",
    attackType: "ranged_spell",
    classes: ["sorcerer", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "magic-missile",
    name: "Mísseis Mágicos",
    nameEn: "Magic Missile",
    level: 1,
    school: "evocation",
    castingTime: "1 ação",
    range: "36 metros",
    components: ["V", "S"],
    duration: "Instantâneo",
    description:
      "Você cria três dardos brilhantes de força mágica. Cada dardo atinge uma criatura à sua escolha que você possa ver dentro do alcance. Um dardo causa 1d4+1 de dano de força ao alvo. Os dardos atingem simultaneamente, e você pode direcioná-los para o mesmo ou para alvos diferentes.",
    higherLevels:
      "Quando conjurada com um espaço de magia de 2º nível ou maior, a magia cria um dardo a mais para cada nível de espaço acima do 1º.",
    ritual: false,
    concentration: false,
    damageDice: "1d4+1",
    damageType: "force",
    attackType: "none",
    classes: ["sorcerer", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "shield",
    name: "Escudo Arcano",
    nameEn: "Shield",
    level: 1,
    school: "abjuration",
    castingTime: "1 reação, que você usa quando é atingido por um ataque ou alvo da magia projétil mágico",
    range: "Pessoal",
    components: ["V", "S"],
    duration: "1 rodada",
    description:
      "Uma barreira invisível de força mágica aparece e o protege. Até o início do seu próximo turno, você tem +5 de bônus na CA, incluindo contra o ataque desencadeador, e não sofre dano de Mísseis Mágicos.",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "cure-wounds",
    name: "Curar Ferimentos",
    nameEn: "Cure Wounds",
    level: 1,
    school: "evocation",
    castingTime: "1 ação",
    range: "Toque",
    components: ["V", "S"],
    duration: "Instantâneo",
    description:
      "Uma criatura que você toque recupera um número de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração. Esta magia não tem efeito sobre mortos-vivos ou constructos.",
    higherLevels:
      "Quando conjurada com um espaço de magia de 2º nível ou maior, a cura aumenta em 1d8 para cada nível acima do 1º.",
    ritual: false,
    concentration: false,
    classes: ["bard", "cleric", "druid", "paladin", "ranger"],
    attribution: ATTR,
  },
  {
    slug: "healing-word",
    name: "Palavra de Cura",
    nameEn: "Healing Word",
    level: 1,
    school: "evocation",
    castingTime: "1 ação bônus",
    range: "18 metros",
    components: ["V"],
    duration: "Instantâneo",
    description:
      "Uma criatura à sua escolha que você possa ver dentro do alcance recupera pontos de vida iguais a 1d4 + seu modificador de habilidade de conjuração. Esta magia não tem efeito sobre mortos-vivos ou constructos.",
    higherLevels:
      "Quando conjurada com um espaço de magia de 2º nível ou maior, a cura aumenta em 1d4 para cada nível acima do 1º.",
    ritual: false,
    concentration: false,
    classes: ["bard", "cleric", "druid"],
    attribution: ATTR,
  },
  {
    slug: "sleep",
    name: "Sono",
    nameEn: "Sleep",
    level: 1,
    school: "enchantment",
    castingTime: "1 ação",
    range: "27 metros",
    components: ["V", "S", "M"],
    materialComponent: "uma pitada de areia fina, pétalas de rosa ou um grilo",
    duration: "1 minuto",
    description:
      "Esta magia faz com que criaturas adormeçam. Role 5d8; o total é o número de pontos de vida de criaturas que esta magia pode afetar. Criaturas a até 6 metros de um ponto à sua escolha dentro do alcance são afetadas em ordem crescente de pontos de vida atuais (ignorando criaturas inconscientes). Mortos-vivos e criaturas imunes a estar Encantadas não são afetadas.",
    higherLevels:
      "Quando conjurada com um espaço de magia de 2º nível ou maior, role 2d8 a mais para cada nível acima do 1º.",
    ritual: false,
    concentration: false,
    classes: ["bard", "sorcerer", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "fireball",
    name: "Bola de Fogo",
    nameEn: "Fireball",
    level: 3,
    school: "evocation",
    castingTime: "1 ação",
    range: "45 metros",
    components: ["V", "S", "M"],
    materialComponent:
      "uma minúscula bola de guano de morcego e enxofre",
    duration: "Instantâneo",
    description:
      "Uma faísca brilhante voa do seu dedo apontado para um ponto à sua escolha dentro do alcance e então floresce em uma explosão de chamas com um rugido baixo. Cada criatura em uma esfera com 6 metros de raio centrada nesse ponto deve realizar um teste de resistência de Destreza. O alvo sofre 8d6 de dano de fogo se falhar, ou metade do dano se acertar.",
    higherLevels:
      "Quando conjurada com um espaço de magia de 4º nível ou maior, o dano aumenta em 1d6 para cada nível acima do 3º.",
    ritual: false,
    concentration: false,
    damageDice: "8d6",
    damageType: "fire",
    saveAttribute: "dex",
    attackType: "none",
    classes: ["sorcerer", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "counterspell",
    name: "Contramágica",
    nameEn: "Counterspell",
    level: 3,
    school: "abjuration",
    castingTime: "1 reação, que você usa quando vê uma criatura a 18 metros de você conjurando uma magia",
    range: "18 metros",
    components: ["S"],
    duration: "Instantâneo",
    description:
      "Você tenta interromper uma criatura no processo de conjurar uma magia. Se a criatura está conjurando uma magia de 3º nível ou inferior, sua magia falha e não tem efeito. Se está conjurando uma magia de 4º nível ou superior, faça um teste de habilidade usando seu atributo de conjuração. A CD é igual a 10 + o nível de magia. Em sucesso, a magia da criatura falha e não tem efeito.",
    higherLevels:
      "Quando conjurada com um espaço de magia de 4º nível ou maior, a magia interrompida não tem efeito se seu nível for menor ou igual ao nível do espaço usado.",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "warlock", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "hold-person",
    name: "Imobilizar Pessoa",
    nameEn: "Hold Person",
    level: 2,
    school: "enchantment",
    castingTime: "1 ação",
    range: "18 metros",
    components: ["V", "S", "M"],
    materialComponent: "um pequeno pedaço reto de ferro",
    duration: "Concentração, até 1 minuto",
    description:
      "Escolha um humanoide que você possa ver dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Sabedoria ou ficará Paralisado pela duração da magia. Ao fim de cada um de seus turnos, o alvo pode tentar um novo teste, encerrando o efeito sobre si em sucesso.",
    higherLevels:
      "Quando conjurada com espaço de magia de 3º nível ou maior, você pode visar um humanoide adicional para cada nível acima do 2º. Os humanoides devem estar a até 9 metros uns dos outros quando você os visar.",
    ritual: false,
    concentration: true,
    saveAttribute: "wis",
    attackType: "none",
    classes: ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "misty-step",
    name: "Passo Brumoso",
    nameEn: "Misty Step",
    level: 2,
    school: "conjuration",
    castingTime: "1 ação bônus",
    range: "Pessoal",
    components: ["V"],
    duration: "Instantâneo",
    description:
      "Brevemente envolto em névoa prateada, você se teletransporta até 9 metros para um espaço desocupado que possa ver.",
    ritual: false,
    concentration: false,
    classes: ["sorcerer", "warlock", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "detect-magic",
    name: "Detectar Magia",
    nameEn: "Detect Magic",
    level: 1,
    school: "divination",
    castingTime: "1 ação",
    range: "Pessoal",
    components: ["V", "S"],
    duration: "Concentração, até 10 minutos",
    description:
      "Pelo tempo da duração, você sente a presença de magia a até 9 metros de você. Se você sentir magia dessa forma, pode usar sua ação para ver uma aura tênue ao redor de qualquer criatura ou objeto visível na área que carregue magia, e você aprende sua escola de magia, se houver.",
    ritual: true,
    concentration: true,
    classes: ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"],
    attribution: ATTR,
  },
  {
    slug: "bless",
    name: "Abençoar",
    nameEn: "Bless",
    level: 1,
    school: "enchantment",
    castingTime: "1 ação",
    range: "9 metros",
    components: ["V", "S", "M"],
    materialComponent: "uma quantidade pequena de água benta",
    duration: "Concentração, até 1 minuto",
    description:
      "Você abençoa até três criaturas à sua escolha dentro do alcance. Sempre que um alvo fizer uma jogada de ataque ou um teste de resistência antes do término da magia, ele pode rolar 1d4 e adicionar o número rolado ao resultado.",
    higherLevels:
      "Quando conjurada com espaço de magia de 2º nível ou maior, você pode visar uma criatura adicional para cada nível acima do 1º.",
    ritual: false,
    concentration: true,
    classes: ["cleric", "paladin"],
    attribution: ATTR,
  },
  {
    slug: "eldritch-blast",
    name: "Rajada Mística",
    nameEn: "Eldritch Blast",
    level: 0,
    school: "evocation",
    castingTime: "1 ação",
    range: "36 metros",
    components: ["V", "S"],
    duration: "Instantâneo",
    description:
      "Um feixe de energia crepitante atinge uma criatura dentro do alcance. Faça uma jogada de ataque mágico à distância contra o alvo. Em um acerto, o alvo sofre 1d10 de dano de força.",
    higherLevels:
      "A magia cria mais de um feixe quando você atinge níveis superiores: dois no 5º (2d10 total), três no 11º e quatro no 17º. Você pode direcionar os feixes para o mesmo alvo ou alvos diferentes.",
    ritual: false,
    concentration: false,
    damageDice: "1d10",
    damageType: "force",
    attackType: "ranged_spell",
    classes: ["warlock"],
    attribution: ATTR,
  },
  {
    slug: "guidance",
    name: "Orientação",
    nameEn: "Guidance",
    level: 0,
    school: "divination",
    castingTime: "1 ação",
    range: "Toque",
    components: ["V", "S"],
    duration: "Concentração, até 1 minuto",
    description:
      "Você toca uma criatura disposta. Uma vez antes do término da magia, o alvo pode rolar 1d4 e adicionar o número rolado a um teste de habilidade à sua escolha. Ele pode rolar o dado antes ou depois do teste. A magia então termina.",
    ritual: false,
    concentration: true,
    classes: ["cleric", "druid"],
    attribution: ATTR,
  },
  {
    slug: "thunderwave",
    name: "Onda Trovejante",
    nameEn: "Thunderwave",
    level: 1,
    school: "evocation",
    castingTime: "1 ação",
    range: "Pessoal (cubo de 4,5 metros)",
    components: ["V", "S"],
    duration: "Instantâneo",
    description:
      "Uma onda de energia trovejante varre uma área a partir de você. Cada criatura em um cubo de 4,5 metros original em você deve fazer um teste de resistência de Constituição. Ao falhar, sofre 2d8 de dano de trovão e é empurrada 3 metros pra longe de você. Ao acertar, sofre metade do dano e não é empurrada.",
    higherLevels:
      "Quando conjurada com espaço de 2º nível ou maior, o dano aumenta em 1d8 para cada nível acima do 1º.",
    ritual: false,
    concentration: false,
    damageDice: "2d8",
    damageType: "thunder",
    saveAttribute: "con",
    attackType: "none",
    classes: ["bard", "druid", "sorcerer", "wizard"],
    attribution: ATTR,
  },
];
