// ── Classes do SRD 5.1 ──
//
// 12 classes do PHB que estão no SRD 5.1. Resumo curto — detalhes
// completos (subclasses, tabela de progressão completa) ficam pra
// fatia que importar do 5e-database.

import type { SrdClassEntry } from "@/types/srd";
import { makeOfficialSrdAttribution } from "./attribution";

const ATTR = makeOfficialSrdAttribution("SRD 5.1 §1");

export const SEED_CLASSES: SrdClassEntry[] = [
  {
    slug: "barbarian", name: "Bárbaro", nameEn: "Barbarian", hitDie: 12,
    primaryAbility: ["str"], savingThrowProficiencies: ["str", "con"],
    armorProficiencies: ["light", "medium", "shield"],
    weaponProficiencies: ["simple", "martial"],
    skillChoiceCount: 2,
    skillChoices: ["athletics", "animal-handling", "intimidation", "nature", "perception", "survival"],
    description: "Guerreiro brutal canalizando fúria primal em combate.",
    attribution: ATTR,
  },
  {
    slug: "bard", name: "Bardo", nameEn: "Bard", hitDie: 8,
    primaryAbility: ["cha"], savingThrowProficiencies: ["dex", "cha"],
    armorProficiencies: ["light"], weaponProficiencies: ["simple", "hand-crossbow", "longsword", "rapier", "shortsword"],
    skillChoiceCount: 3,
    skillChoices: ["acrobatics", "animal-handling", "arcana", "athletics", "deception", "history", "insight", "intimidation", "investigation", "medicine", "nature", "perception", "performance", "persuasion", "religion", "sleight-of-hand", "stealth", "survival"],
    spellcastingAbility: "cha",
    description: "Conjurador inspirador que tece magia em palavras e música.",
    attribution: ATTR,
  },
  {
    slug: "cleric", name: "Clérigo", nameEn: "Cleric", hitDie: 8,
    primaryAbility: ["wis"], savingThrowProficiencies: ["wis", "cha"],
    armorProficiencies: ["light", "medium", "shield"], weaponProficiencies: ["simple"],
    skillChoiceCount: 2,
    skillChoices: ["history", "insight", "medicine", "persuasion", "religion"],
    spellcastingAbility: "wis",
    description: "Servo divino que canaliza poder de uma divindade.",
    attribution: ATTR,
  },
  {
    slug: "druid", name: "Druida", nameEn: "Druid", hitDie: 8,
    primaryAbility: ["wis"], savingThrowProficiencies: ["int", "wis"],
    armorProficiencies: ["light", "medium", "shield (não-metálicos)"],
    weaponProficiencies: ["clubs", "daggers", "darts", "javelins", "maces", "quarterstaffs", "scimitars", "sickles", "slings", "spears"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "animal-handling", "insight", "medicine", "nature", "perception", "religion", "survival"],
    spellcastingAbility: "wis",
    description: "Sacerdote da natureza com poder druídico ancestral.",
    attribution: ATTR,
  },
  {
    slug: "fighter", name: "Guerreiro", nameEn: "Fighter", hitDie: 10,
    primaryAbility: ["str", "dex"], savingThrowProficiencies: ["str", "con"],
    armorProficiencies: ["light", "medium", "heavy", "shield"],
    weaponProficiencies: ["simple", "martial"],
    skillChoiceCount: 2,
    skillChoices: ["acrobatics", "animal-handling", "athletics", "history", "insight", "intimidation", "perception", "survival"],
    description: "Mestre do combate, treinado em todas as armas e armaduras.",
    attribution: ATTR,
  },
  {
    slug: "monk", name: "Monge", nameEn: "Monk", hitDie: 8,
    primaryAbility: ["dex", "wis"], savingThrowProficiencies: ["str", "dex"],
    armorProficiencies: [], weaponProficiencies: ["simple", "shortsword"],
    skillChoiceCount: 2,
    skillChoices: ["acrobatics", "athletics", "history", "insight", "religion", "stealth"],
    description: "Mestre das artes marciais que canaliza energia ki.",
    attribution: ATTR,
  },
  {
    slug: "paladin", name: "Paladino", nameEn: "Paladin", hitDie: 10,
    primaryAbility: ["str", "cha"], savingThrowProficiencies: ["wis", "cha"],
    armorProficiencies: ["light", "medium", "heavy", "shield"],
    weaponProficiencies: ["simple", "martial"],
    skillChoiceCount: 2,
    skillChoices: ["athletics", "insight", "intimidation", "medicine", "persuasion", "religion"],
    spellcastingAbility: "cha",
    description: "Guerreiro sagrado, juramentos e magia divina em combate.",
    attribution: ATTR,
  },
  {
    slug: "ranger", name: "Patrulheiro", nameEn: "Ranger", hitDie: 10,
    primaryAbility: ["dex", "wis"], savingThrowProficiencies: ["str", "dex"],
    armorProficiencies: ["light", "medium", "shield"],
    weaponProficiencies: ["simple", "martial"],
    skillChoiceCount: 3,
    skillChoices: ["animal-handling", "athletics", "insight", "investigation", "nature", "perception", "stealth", "survival"],
    spellcastingAbility: "wis",
    description: "Caçador da natureza, hábil em rastreamento e ataque à distância.",
    attribution: ATTR,
  },
  {
    slug: "rogue", name: "Ladino", nameEn: "Rogue", hitDie: 8,
    primaryAbility: ["dex"], savingThrowProficiencies: ["dex", "int"],
    armorProficiencies: ["light"],
    weaponProficiencies: ["simple", "hand-crossbow", "longsword", "rapier", "shortsword"],
    skillChoiceCount: 4,
    skillChoices: ["acrobatics", "athletics", "deception", "insight", "intimidation", "investigation", "perception", "performance", "persuasion", "sleight-of-hand", "stealth"],
    description: "Especialista em furtividade, perícia e ataques precisos.",
    attribution: ATTR,
  },
  {
    slug: "sorcerer", name: "Feiticeiro", nameEn: "Sorcerer", hitDie: 6,
    primaryAbility: ["cha"], savingThrowProficiencies: ["con", "cha"],
    armorProficiencies: [],
    weaponProficiencies: ["dagger", "dart", "sling", "quarterstaff", "light crossbow"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "deception", "insight", "intimidation", "persuasion", "religion"],
    spellcastingAbility: "cha",
    description: "Magia inata, fluindo de uma origem ancestral ou cósmica.",
    attribution: ATTR,
  },
  {
    slug: "warlock", name: "Bruxo", nameEn: "Warlock", hitDie: 8,
    primaryAbility: ["cha"], savingThrowProficiencies: ["wis", "cha"],
    armorProficiencies: ["light"], weaponProficiencies: ["simple"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "deception", "history", "intimidation", "investigation", "nature", "religion"],
    spellcastingAbility: "cha",
    description: "Pacto com entidade extraplanar concede magia e poderes únicos.",
    attribution: ATTR,
  },
  {
    slug: "wizard", name: "Mago", nameEn: "Wizard", hitDie: 6,
    primaryAbility: ["int"], savingThrowProficiencies: ["int", "wis"],
    armorProficiencies: [],
    weaponProficiencies: ["dagger", "dart", "sling", "quarterstaff", "light crossbow"],
    skillChoiceCount: 2,
    skillChoices: ["arcana", "history", "insight", "investigation", "medicine", "religion"],
    spellcastingAbility: "int",
    description: "Estudioso da arte arcana, conjurando do grimório.",
    attribution: ATTR,
  },
];
