// ── Seed mock de itens do SRD 5.1 ──
//
// 12 itens variando armas, armaduras e mágicos básicos. SRD 5.1 (CC-BY 4.0).

import type { SrdItem } from "@/types/srd";
import { makeOfficialSrdAttribution } from "./attribution";

const ATTR = makeOfficialSrdAttribution("SRD 5.1 §3");

export const SEED_ITEMS: SrdItem[] = [
  {
    slug: "longsword",
    name: "Espada Longa",
    nameEn: "Longsword",
    category: "weapon",
    subcategory: "MARTIAL_MELEE",
    cost: { quantity: 15, unit: "gp" },
    weight: 1.5,
    damageDice: "1d8",
    damageType: "slashing",
    weaponProperties: ["versatile (1d10)"],
    weaponRange: { normal: 5 },
    description: "Espada marcial com lâmina reta e dois gumes.",
    attribution: ATTR,
  },
  {
    slug: "rapier",
    name: "Rapieira",
    nameEn: "Rapier",
    category: "weapon",
    subcategory: "MARTIAL_MELEE",
    cost: { quantity: 25, unit: "gp" },
    weight: 1,
    damageDice: "1d8",
    damageType: "piercing",
    weaponProperties: ["finesse"],
    weaponRange: { normal: 5 },
    description: "Lâmina fina e flexível usada para estocadas precisas.",
    attribution: ATTR,
  },
  {
    slug: "dagger",
    name: "Adaga",
    nameEn: "Dagger",
    category: "weapon",
    subcategory: "SIMPLE_MELEE",
    cost: { quantity: 2, unit: "gp" },
    weight: 0.5,
    damageDice: "1d4",
    damageType: "piercing",
    weaponProperties: ["finesse", "light", "thrown"],
    weaponRange: { normal: 20, long: 60 },
    description: "Pequena lâmina de mão dupla, fácil de esconder e arremessar.",
    attribution: ATTR,
  },
  {
    slug: "longbow",
    name: "Arco Longo",
    nameEn: "Longbow",
    category: "weapon",
    subcategory: "MARTIAL_RANGED",
    cost: { quantity: 50, unit: "gp" },
    weight: 1,
    damageDice: "1d8",
    damageType: "piercing",
    weaponProperties: ["ammunition", "heavy", "two-handed"],
    weaponRange: { normal: 150, long: 600 },
    description: "Arco grande para uso em campo aberto.",
    attribution: ATTR,
  },
  {
    slug: "leather-armor",
    name: "Armadura de Couro",
    nameEn: "Leather Armor",
    category: "armor",
    subcategory: "LIGHT_ARMOR",
    cost: { quantity: 10, unit: "gp" },
    weight: 4.5,
    armorClass: { base: 11, dexBonus: true },
    description:
      "Armadura leve feita de couro endurecido. Não impõe penalidade em Furtividade.",
    attribution: ATTR,
  },
  {
    slug: "chain-mail",
    name: "Cota de Malha",
    nameEn: "Chain Mail",
    category: "armor",
    subcategory: "HEAVY_ARMOR",
    cost: { quantity: 75, unit: "gp" },
    weight: 25,
    armorClass: { base: 16, dexBonus: false },
    strengthRequirement: 13,
    stealthDisadvantage: true,
    description: "Armadura pesada de pequenos anéis de aço entrelaçados.",
    attribution: ATTR,
  },
  {
    slug: "plate-armor",
    name: "Armadura de Placas",
    nameEn: "Plate Armor",
    category: "armor",
    subcategory: "HEAVY_ARMOR",
    cost: { quantity: 1500, unit: "gp" },
    weight: 30,
    armorClass: { base: 18, dexBonus: false },
    strengthRequirement: 15,
    stealthDisadvantage: true,
    description:
      "Armadura completa de placas de aço sobre uma camada de cota de malha.",
    attribution: ATTR,
  },
  {
    slug: "shield",
    name: "Escudo",
    nameEn: "Shield",
    category: "armor",
    subcategory: "SHIELD",
    cost: { quantity: 10, unit: "gp" },
    weight: 3,
    armorClass: { base: 2, dexBonus: false },
    description: "Escudo carregado em uma das mãos. Concede +2 de bônus na CA.",
    attribution: ATTR,
  },
  {
    slug: "potion-of-healing",
    name: "Poção de Cura",
    nameEn: "Potion of Healing",
    category: "magic-item",
    cost: { quantity: 50, unit: "gp" },
    weight: 0.25,
    rarity: "common",
    requiresAttunement: false,
    description:
      "Você recupera 2d4+2 pontos de vida ao beber esta poção. O líquido reluz à luz.",
    attribution: ATTR,
  },
  {
    slug: "bag-of-holding",
    name: "Saco de Conter",
    nameEn: "Bag of Holding",
    category: "magic-item",
    weight: 7.5,
    rarity: "uncommon",
    requiresAttunement: false,
    description:
      "Este saco tem um interior dimensional maior que seu exterior. Pode conter até 250 kg, com volume de até 1900 litros. Sempre pesa 7,5 kg.",
    attribution: ATTR,
  },
  {
    slug: "ring-of-protection",
    name: "Anel da Proteção",
    nameEn: "Ring of Protection",
    category: "magic-item",
    rarity: "rare",
    requiresAttunement: true,
    description:
      "Você ganha +1 de bônus na CA e em testes de resistência enquanto usa este anel.",
    attribution: ATTR,
  },
  {
    slug: "thieves-tools",
    name: "Ferramentas de Ladrão",
    nameEn: "Thieves' Tools",
    category: "tool",
    cost: { quantity: 25, unit: "gp" },
    weight: 0.5,
    description:
      "Inclui uma pequena lima, ganchos, um espelho dobrável montado em uma haste de metal, tesouras estreitas e gazuas. Proficiência permite testes de Destreza para destrancar ou desarmar armadilhas.",
    attribution: ATTR,
  },
];
