import type { Achievement } from "@/types/profile";

export const ACHIEVEMENTS: Achievement[] = [
  // ── Combat ──
  {
    id: "first-blood",
    name: "Primeiro Sangue",
    description: "Derrote seu primeiro inimigo em combate.",
    category: "combat",
    tier: "bronze",
    icon: "Swords",
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    unlockedAt: "2025-06-15",
  },
  {
    id: "critical-master",
    name: "Mestre dos Críticos",
    description: "Acerte 20 ataques críticos.",
    category: "combat",
    tier: "gold",
    icon: "Zap",
    progress: 14,
    maxProgress: 20,
    unlocked: false,
  },
  {
    id: "dragon-slayer",
    name: "Matador de Dragões",
    description: "Derrote um dragão em combate.",
    category: "combat",
    tier: "platinum",
    icon: "Flame",
    progress: 0,
    maxProgress: 1,
    unlocked: false,
  },
  {
    id: "survivor",
    name: "Sobrevivente",
    description: "Sobreviva a 10 encontros com HP abaixo de 25%.",
    category: "combat",
    tier: "silver",
    icon: "Heart",
    progress: 7,
    maxProgress: 10,
    unlocked: false,
  },

  // ── Social ──
  {
    id: "silver-tongue",
    name: "Língua de Prata",
    description: "Resolva 5 encontros apenas com diplomacia.",
    category: "social",
    tier: "silver",
    icon: "MessageCircle",
    progress: 5,
    maxProgress: 5,
    unlocked: true,
    unlockedAt: "2025-11-20",
  },
  {
    id: "party-leader",
    name: "Líder do Grupo",
    description: "Seja votado líder do grupo 3 vezes.",
    category: "social",
    tier: "bronze",
    icon: "Crown",
    progress: 2,
    maxProgress: 3,
    unlocked: false,
  },
  {
    id: "backstory-writer",
    name: "Escritor de Backstory",
    description: "Crie 3 personagens com backstory detalhada.",
    category: "social",
    tier: "bronze",
    icon: "BookOpen",
    progress: 3,
    maxProgress: 3,
    unlocked: true,
    unlockedAt: "2025-09-10",
  },
  {
    id: "roleplay-king",
    name: "Rei do Roleplay",
    description: "Participe de 50 sessões com roleplay ativo.",
    category: "social",
    tier: "gold",
    icon: "Theater",
    progress: 32,
    maxProgress: 50,
    unlocked: false,
  },

  // ── Exploration ──
  {
    id: "cartographer",
    name: "Cartógrafo",
    description: "Explore 10 mapas diferentes.",
    category: "exploration",
    tier: "silver",
    icon: "Map",
    progress: 10,
    maxProgress: 10,
    unlocked: true,
    unlockedAt: "2026-01-05",
  },
  {
    id: "treasure-hunter",
    name: "Caçador de Tesouros",
    description: "Encontre 25 itens lendários.",
    category: "exploration",
    tier: "gold",
    icon: "Gem",
    progress: 8,
    maxProgress: 25,
    unlocked: false,
  },
  {
    id: "dungeon-delver",
    name: "Explorador de Masmorras",
    description: "Complete 15 masmorras.",
    category: "exploration",
    tier: "silver",
    icon: "Compass",
    progress: 11,
    maxProgress: 15,
    unlocked: false,
  },

  // ── GM ──
  {
    id: "first-session",
    name: "Primeira Sessão",
    description: "Mestre sua primeira sessão de RPG.",
    category: "gm",
    tier: "bronze",
    icon: "Shield",
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    unlockedAt: "2025-05-20",
  },
  {
    id: "world-builder",
    name: "Construtor de Mundos",
    description: "Crie 5 campanhas diferentes.",
    category: "gm",
    tier: "gold",
    icon: "Globe",
    progress: 3,
    maxProgress: 5,
    unlocked: false,
  },
  {
    id: "five-star-gm",
    name: "Mestre 5 Estrelas",
    description: "Receba avaliação média de 5 estrelas com 10+ reviews.",
    category: "gm",
    tier: "platinum",
    icon: "Star",
    progress: 7,
    maxProgress: 10,
    unlocked: false,
  },
  {
    id: "encounter-designer",
    name: "Designer de Encontros",
    description: "Crie 50 encontros de combate.",
    category: "gm",
    tier: "silver",
    icon: "Crosshair",
    progress: 28,
    maxProgress: 50,
    unlocked: false,
  },

  // ── Meta ──
  {
    id: "veteran",
    name: "Veterano",
    description: "Jogue 100 sessões no QuestBoard.",
    category: "meta",
    tier: "gold",
    icon: "Trophy",
    progress: 42,
    maxProgress: 100,
    unlocked: false,
  },
  {
    id: "early-adopter",
    name: "Early Adopter",
    description: "Crie uma conta no primeiro mês do QuestBoard.",
    category: "meta",
    tier: "gold",
    icon: "Sparkles",
    progress: 1,
    maxProgress: 1,
    unlocked: true,
    unlockedAt: "2025-04-01",
  },
  {
    id: "completionist",
    name: "Completionista",
    description: "Desbloqueie todas as outras conquistas.",
    category: "meta",
    tier: "platinum",
    icon: "Award",
    progress: 6,
    maxProgress: 17,
    unlocked: false,
  },
  {
    id: "profile-customizer",
    name: "Personalizador",
    description: "Equipe pelo menos 3 cosméticos diferentes.",
    category: "meta",
    tier: "bronze",
    icon: "Palette",
    progress: 3,
    maxProgress: 3,
    unlocked: true,
    unlockedAt: "2025-07-01",
  },
];
